# Generated by Django 5.2.17 on 2026-08-31 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('image_name', models.CharField(max_length=255)),
                ('image_content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('image_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, default='')),
                ('user_prompt', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('api_defaults', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('error', 'Error')], default='in_progress', max_length=20)),
                ('vision_model_id', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=32)),
                ('api_model', models.CharField(max_length=100)),
                ('response_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_type', models.CharField(blank=True, max_length=255)),
                ('provider_response_id', models.CharField(blank=True, max_length=255)),
                ('response_model', models.CharField(blank=True, max_length=100)),
                ('provider_status', models.CharField(blank=True, max_length=50)),
                ('request_started_at', models.DateTimeField(blank=True, null=True)),
                ('request_finished_at', models.DateTimeField(blank=True, null=True)),
                ('latency_wall_seconds', models.FloatField(blank=True, null=True)),
                ('latency_provider_seconds', models.FloatField(blank=True, null=True)),
                ('time_to_first_token_seconds', models.FloatField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('reasoning_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cached_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_write_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_raw', models.JSONField(blank=True, default=dict)),
                ('api_request', models.JSONField(blank=True, default=dict)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
